# Generated by superflore -- DO NOT EDIT
#
# Copyright 2019 Open Source Robotics Foundation
# Distributed under the terms of the BSD license

DESCRIPTION = "A minimal service server which adds two numbers"
AUTHOR = "Mikael Arguedas <mikael@osrfoundation.org>"
HOMEPAGE = "https://wiki.ros.org"
SECTION = "devel"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://package.xml;beginline=8;endline=8;md5=12c26a18c7f493fdc7e8a93b16b7c04f"

ROS_BUILD_DEPENDS = "example-interfaces rclcpp"
DEPENDS = "${ROS_BUILD_DEPENDS}"

ROS_BUILDTOOL_DEPENDS = "ament-cmake-native"
DEPENDS += "${ROS_BUILDTOOL_DEPENDS}"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = ""

SRC_URI = "https://github.com/ros2-gbp/examples-release/archive/release/bouncy/examples_rclcpp_minimal_service/0.5.1-0.tar.gz;downloadfilename=${ROS_SP}.tar.gz"
SRC_URI[md5sum] = "910f53eb49fef5225c4940d14c934e57"
SRC_URI[sha256sum] = "6ed98e35b6e0afbb218fcd0da6cafbfbda8969fee4afa6ca20843eda42008b42"
S = "${WORKDIR}/examples-release-release-bouncy-examples_rclcpp_minimal_service-0.5.1-0"

ROS_BUILD_TYPE = "ament_cmake"
ROS_RECIPES_TREE = "recipes-ros2"

# Allow the above settings to be overridden.
include ${ROS_LAYERDIR}/recipes-ros/examples-rclcpp-minimal-service/examples-rclcpp-minimal-service-common.inc
include ${ROS_LAYERDIR}/recipes-ros2/examples-rclcpp-minimal-service/examples-rclcpp-minimal-service-common.inc
include ${ROS_LAYERDIR}/${ROS_RECIPES_TREE}/examples-rclcpp-minimal-service/examples-rclcpp-minimal-service-common-${PV}.inc
include ${ROS_LAYERDIR}/${ROS_RECIPES_TREE}/examples-rclcpp-minimal-service/${BPN}.inc
include ${ROS_LAYERDIR}/${ROS_RECIPES_TREE}/examples-rclcpp-minimal-service/${BPN}-${PV}.inc

inherit ros_bouncy
inherit ros_${ROS_BUILD_TYPE}

